apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: chartie-chart
version: 0.1.0
maintainers:
    - name: Mohammed
      email: mohammad10596@gmail.com
      url: mohammedalameen.com

